db-uri = "postgres://authenticator:authpass@localhost:5432/hackathon_s4"
db-schemas = "public"
db-anon-role = "anon"
jwt-secret = "super-secret-jwt-token-for-hackathon-s4-demo-only-32b"
server-port = 3000
